### ISSUE TITLE
Demo example not working properly

### ISSUE THREAD

**Issue by mahn00r-malik** [billzorn/sfpy#1]
I executed the statement a*b - a/b . It results in the following error

"TypeError: unsupported operand type(s) for /: 'sfpy.float.Float16' and 'sfpy.float.Float16'

**Comment by mahn00r-malik** [comment]
It is supported when I use python3.5 .Previously , it was not working with python 2.7

**Comment by billzorn** [comment]
Ah, this is because Python2 and Python3 handle the division operator differently... To fix this, do
```
from __future__ import division
```
to use the Python3 division conventions.

Another workaround is to use the division methods directly, either as `a.div(b)` or `sfpy.float.f16_div(a, b)` (depending on the datatype).
